### PR TITLE
Excluded modules should not be added to task graph

### LINKED ISSUE #159: excludedModules is not working with custom task.
### Environment
- macOS 12.5
- Gradle 7.5
- AMD 0.1.6
- AGP 7.2.1
- Detekt 1.21.0
- Java 17
- Kotlin 1.6.21

### Description
I'm integrating AMD into my project and I created two custom tasks. When I run `./gradlew runAffectedDetekt', I'm getting this error even though **linter** is specified in the excludedModules.

```
* What went wrong:
Could not determine the dependencies of task ':runAffectedDetekt'.
> Task with path ':linter:detekt' not found in root project 'Rappi-Android-User'.
```

This error makes sense since Detekt is not applied in the linter module; however, it should be ignored by AMD if it's specified in the excluded modules.

### Configuration
```
    import com.dropbox.affectedmoduledetector.AffectedModuleConfiguration

    apply plugin: "com.dropbox.affectedmoduledetector"

    def branch = System.getenv('DESTINATION_BRANCH')
    if (!branch) {
        branch = "origin/develop"
    }

    logger.lifecycle("Destination branch: $branch")

    affectedModuleDetector {
        baseDir = "${project.rootDir}"
        pathsAffectingAllModules = [
                "tools/global-dependencies.gradle"
        ]
        logFilename = "output.log"
        logFolder = "${project.rootDir}"
        specifiedBranch = "$branch"
        compareFrom = "SpecifiedBranchCommit"
        excludedModules = ["linter", ":linter"]
        customTasks = [
                new AffectedModuleConfiguration.CustomTask(
                        "runAffectedDetekt,
                        "detekt",
                        "Run detekt"
                ),
                new AffectedModuleConfiguration.CustomTask(
                        "runAffectedAndroidLint",
                        "lintDebug",
                        "Run lint"
                ),
        ]
```

### PR DESCRIPTION
**Pull request by joshafeinberg**
Fixes #159 

I believe this fix should handle excluded modules not being added at all to the task graph by checking the configuration before adding it

### CODE REVIEW

File: affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPlugin.kt [hunk 1]
```diff
@@ -77,10 +77,7 @@ class AffectedModuleDetectorPlugin : Plugin<Project> {
     }
 
     private fun registerCustomTasks(rootProject: Project) {
-        val mainConfiguration = requireNotNull(
-            value = rootProject.extensions.findByName(AffectedModuleConfiguration.name),
-            lazyMessage = {  "Unable to find ${AffectedTestConfiguration.name} in $rootProject" }
-        ) as AffectedModuleConfiguration
+        val mainConfiguration = requireConfiguration(rootProject)
```
Comment (Evleaps) [inline affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPlugin.kt:80]: this method calls quite often in big multymodule projects. 
1) too much boilerplate 
2) [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself#:~:text=The%20DRY%20principle%20is%20stated,their%20book%20The%20Pragmatic%20Programmer.)
3) we can do  small optimization with singleton

Comment (Evleaps) [reply affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPlugin.kt:80]: I recognized your comments in my previous PR. Actually, I was wrong. Thank u for the explanation.  

I closed my previous PR, a bit pity my time. But it is the right way. 

We can merge your version for solving the problem.

**Review by chris-mitchell — APPROVED** [review]
